name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - name: Determine npm dist-tag from git tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME#v}"
          DIST_TAG="latest"

          # Example:
          # 15.5.0 -> latest
          # 15.5.0-alpha.1 -> alpha
          # 15.5.0-beta.1 -> beta
          if [[ "$TAG_NAME" == *-* ]]; then
            PRERELEASE_PART="${TAG_NAME#*-}"
            DIST_TAG="${PRERELEASE_PART%%.*}"
          fi

          echo "DIST_TAG=$DIST_TAG" >> "$GITHUB_ENV"

      - name: Publish package to npm
        run: npm publish --tag "$DIST_TAG"